# Generated by Django 2.1.4 on 2019-01-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangjobs',
            old_name='comoany',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='chennaijobs',
            old_name='comoany',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='comoany',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='comoany',
            new_name='company',
        ),
    ]
